name: CI build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_nuget:
    runs-on: ubuntu-latest

    env:
      DOTNET_NOLOGO: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0"

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore
#    - name: Test
#      run: dotnet test --no-restore --verbosity normal

      - name: Pack
        run: dotnet pack ./src/GiphyCli.csproj -c Release -o ./artifacts --no-build

      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: artifacts/**/*

  build_docker:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io

    permissions:
      contents: read
      packages: write

    steps:
      - name: Docker Login
        uses: docker/login-action@v1.12.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: |
            ghcr.io/daviddesloovere/giphy-cli:latest
            ghcr.io/daviddesloovere/giphy-cli:$(date +%s)
